### ISSUE TITLE
Legacy Bestiary Compendium contents not showing up in Forge?

### ISSUE THREAD

**Issue by RandallCarter8100** [dogstarrb/pf2e-legacy-content#10]
Have updated the mod on both my Foundry PC install and in the Forge. PC version shows all Compendium content for Legacy Bestiary 1-3.  However on the Forge, the Compendium folder is empty. Is there anything that can be done?

Forge Version
![image](https://github.com/user-attachments/assets/80740ad9-4a27-4363-a05c-44a84ddb444c)

PC only version:
![image](https://github.com/user-attachments/assets/7fcca5c1-4bc0-447f-a82f-8aea46b5d914)

**Comment by kakaroto** [comment]
I investigated this and it looks like the devs made two releases (at about 5 hours interval between the two), the first one was broken without the bestiaries compendium content, and the second one is correct.

The issue is that the second release uses the same version number as the first. This is not something we support and for technical reasons (that would take a few pages of text to explain the intricacies of why), it's simply impossible to "update the cache for that version of the module" on The Forge's systems.
In other words, versions are immutable (as a concept, in general, but also for technical reasons on the Forge, and on some other platforms), and you simply cannot have two different versions sharing the same version number.

Other users of the module who would have updated/installed it when 1.1 version was released (the first version of 1.1, not the second version of 1.1) would be in the same situation and wouldn't know that the only way to solve it is to fully uninstall the module and re-install it.

Also, there was a 1.1.0 release 1 year ago, then the 1.1 release 1 week ago. The versioning numbers are kind of weird and don't follow semantic versioning.

Basically the solution here is for the module devs to bump the version number of their module and re-release it and adhere to the best practices of keeping each version immutable.
I hope this helps!

**Comment by RandallCarter8100** [comment]
Thank you.  Have you forwarded this to the developer or should i?

**Comment by dogstarrb** [comment]
I'm looped in and should have a fix ready soon.

**Comment by RandallCarter8100** [comment]
Awesome, thanks for the update!

**Comment by RandallCarter8100** [comment]
Confirming Legacy Bestiary working as intended now in Foge!  Thanks!!!
